// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2025/11/12 11:40:07
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["E:/OneDrive/Desktop/mvp/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/OneDrive/Desktop/mvp/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/OneDrive/Desktop/mvp/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/OneDrive/Desktop/mvp/frontend/plugins/**/*.{js,ts,mjs}","E:/OneDrive/Desktop/mvp/frontend/stores/**/*.{js,ts,mjs}","E:/OneDrive/Desktop/mvp/frontend/composables/**/*.{js,ts,mjs}","E:/OneDrive/Desktop/mvp/frontend/utils/**/*.{js,ts,mjs}","E:/OneDrive/Desktop/mvp/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/OneDrive/Desktop/mvp/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","E:/OneDrive/Desktop/mvp/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","E:/OneDrive/Desktop/mvp/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;