# Generated by Django 5.2.5 on 2025-09-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_avatar_customuser_nickname"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="language",
            field=models.CharField(default="en", max_length=10),
        ),
        migrations.AddField(
            model_name="customuser",
            name="theme",
            field=models.CharField(default="light", max_length=10),
        ),
    ]
