# Generated by Django 5.0.11 on 2025-09-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_allow_friend_requests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='qq_openid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='wechat_openid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
