# Generated by Django 5.0.11 on 2025-09-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_qq_openid_customuser_wechat_openid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='age_range',
            field=models.CharField(blank=True, choices=[('under_18', '18岁以下'), ('18_25', '18-25岁'), ('26_35', '26-35岁'), ('36_45', '36-45岁'), ('46_55', '46-55岁'), ('over_55', '55岁以上'), ('prefer_not_say', '不愿透露')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='alipay_openid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='douyin_openid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', '男'), ('female', '女'), ('other', '其他'), ('prefer_not_say', '不愿透露')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='occupation',
            field=models.CharField(blank=True, choices=[('student', '学生'), ('teacher', '教师'), ('engineer', '工程师'), ('doctor', '医生'), ('business', '商务人员'), ('government', '政府工作人员'), ('freelancer', '自由职业者'), ('retired', '退休人员'), ('other', '其他'), ('prefer_not_say', '不愿透露')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='platform_username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
